=== markhhoover/BaseRepository2023Beta/src/main/deploy/states/stateData.dtd
<!ELEMENT statedata ( controlData*, mechanismTarget* )>

<!ELEMENT controlData EMPTY>
<!ATTLIST controlData
          identifier CDATA  #REQUIRED
          mode ( PERCENT_OUTPUT | VELOCITY_INCH | VELOCITY_DEGREES  | VELOCITY_RPS |
                 VOLTAGE | CURRENT | TRAPEZOID | MOTION_PROFILE | MOTION_PROFILE_ARC | POSITION_DEGREES) "PERCENT_OUTPUT"
	   constrolServer ( MOTORCONTROLLER | ROBORIO ) "MOTORCONTROLLER"
          proportional CDATA "0.0"
          integral CDATA "0.0"
          derivative CDATA "0.0"
          feedforward CDATA "0.0"
          izone CDATA "0.0"
          maxacceleration CDATA "0.0"
          cruisevelocity CDATA "0.0"
> 

<!ELEMENT mechanismTarget EMPTY>
<!ATTLIST mechanismTarget 
          stateIdentifier ( INTAKE_OFF | INTAKE_ON | INTAKE_EXPEL | INTAKE_RETRACT |
                            SHOOTER_OFF | SHOOT_LOWGOAL | MANUAL_SHOOT | ADJUSTHOOD | PREPARETOSHOOT | SHOOT_HIGHGOAL_CLOSE | SHOOT_HIGHGOAL_FAR | 
                            CLIMBER_OFF | CLIMBER_MANUAL | CLIMBER_INITIALREACH | CLIMBER_RETRACT | CLIMBER_RELEASE | CLIMBER_REACHTOBAR | CLIMBER_ROTATEOUT | CLIMBER_ROTATEIN | CLIMBER_HOLD |
                            LIFT_LIFT | LIFT_LOWER | LIFT_OFF |
                            INDEXER_INDEX | INDEXER_EXPEL | INDEXER_OFF |
                            UNKNOWN ) "UNKNOWN"
          controlDataIdentifier         CDATA #REQUIRED
          controlDataIdentifier2        CDATA #IMPLIED
          value                         CDATA #REQUIRED
          secondValue                   CDATA #IMPLIED
          solenoid                      ( NONE | ON | REVERSE ) "NONE"
>

=== markhhoover/BaseRepository2023Beta/src/main/deploy/states/shooter.xml
<?xml version="1.0"?>
<!DOCTYPE statedata SYSTEM "stateData.dtd">
<statedata>
	<controlData identifier="openloop" 
	             mode="PERCENT_OUTPUT"/>
				 
	<controlData identifier="closedloop"
				 mode="VELOCITY_RPS"
				 proportional="0.095"
				 integral="0.0005"
				 feedforward="0.0385"/>
	<controlData identifier="closedloop2"
				 mode="VELOCITY_RPS"
				 proportional="0.145"
				 integral="0.00075"
				 feedforward="0.0475"/>

	<mechanismTarget stateIdentifier="SHOOTER_OFF"
	                 controlDataIdentifier="openloop"
	                 controlDataIdentifier2="openloop"
					 value="0.0"
					 secondValue="0.0"/>

 	<mechanismTarget stateIdentifier="SHOOT_HIGHGOAL_CLOSE"
	                 controlDataIdentifier="closedloop2"
	                 controlDataIdentifier2="closedloop"
					 value="45.0"
					 secondValue="37"/> 

 	<mechanismTarget stateIdentifier="SHOOT_HIGHGOAL_FAR"
	                 controlDataIdentifier="closedloop2"
	                 controlDataIdentifier2="closedloop"
					 value="45.0"
					 secondValue="37"/> 

	<mechanismTarget stateIdentifier="SHOOT_LOWGOAL"
	                 controlDataIdentifier="openloop"
	                 controlDataIdentifier2="openloop"
					 value="0.3" 
					 secondValue="0.3"/> 

	<mechanismTarget stateIdentifier="MANUAL_SHOOT"
	                 controlDataIdentifier="closedloop2"
	                 controlDataIdentifier2="closedloop"
					 value="24"
					 secondValue="22"/>

	<mechanismTarget stateIdentifier="PREPARETOSHOOT"
	                 controlDataIdentifier="closedloop2"
	                 controlDataIdentifier2="closedloop"
					 value="24"
					 secondValue="22"/>


</statedata>

=== markhhoover/BaseRepository2023Beta/src/main/deploy/states/climber.xml
<?xml version="1.0"?>
<!DOCTYPE statedata SYSTEM "stateData.dtd">
<statedata>
	<controlData identifier="openloop" 
	             mode="PERCENT_OUTPUT"/>
				 
	<controlData identifier="closedloopposdegrees"
				 mode="POSITION_DEGREES"
				 proportional="0.003"/>
				 
	<controlData identifier="closedloopposinches"
				 mode="POSITION_INCH"
				 proportional="0.03"/>

	<controlData identifier="closedloopvel"
				 mode="VELOCITY_RPS"
				 proportional="0.155"
				 feedforward="0.045"/>

	<mechanismTarget stateIdentifier="OFF"
	                 controlDataIdentifier="openloop"
	                 controlDataIdentifier2="openloop"
					 value="0.0"
					 secondValue="0.0"
					 robotPitch="0.0"/>

	<mechanismTarget stateIdentifier="STARTING_CONFIG"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="0.0"
					 secondValue="0.0"
					 robotPitch="0.0"/>

	<mechanismTarget stateIdentifier="MANUAL"
	                 controlDataIdentifier="openloop"
	                 controlDataIdentifier2="openloop"
					 value="0.0"
					 secondValue="0.0"
					 robotPitch="0.0"/>

	<mechanismTarget stateIdentifier="PREP_MID_BAR"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="19.0"
					 secondValue="0.0"
					 robotPitch="0.0"/>

	<mechanismTarget stateIdentifier="CLIMB_MID_BAR"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="1.0"
					 secondValue="0.0"
					 robotPitch="-12.1"/>

	<mechanismTarget stateIdentifier="FRONT_HOOK_PREP_FOR_NEXT_BAR"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="10.0"
					 secondValue="0.0"
					 robotPitch="-12.1"/>

	<mechanismTarget stateIdentifier="FRONT_HOOK_ROTATE_A"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="10.0"
					 secondValue="53.0"
					 robotPitch="6.5"/>

	<mechanismTarget stateIdentifier="FRONT_HOOK_ROTATE_B"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="1.0"
					 secondValue="103.0"
					 robotPitch="24.1"/>

	<mechanismTarget stateIdentifier="FRONT_HOOK_ELEVATE"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="19.0"
					 secondValue="103.0"
					 robotPitch="24.1"/>

	<mechanismTarget stateIdentifier="FRONT_HOOK_ROTATE_TO_HOOK"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="19.0"
					 secondValue="80.0"
					 robotPitch="16.8"/>

	<mechanismTarget stateIdentifier="FRONT_HOOK_LIFT_ROBOT"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="10.0"
					 secondValue="80.0"
					 robotPitch="16.8"/>

	<mechanismTarget stateIdentifier="FRONT_HOOK_ROTATE_ARM"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="10.0"
					 secondValue="0.0"
					 robotPitch="-12.1"/>

	<mechanismTarget stateIdentifier="BACK_HOOK_PREP"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="19.0"
					 secondValue="0.0"
					 robotPitch="-12.1"/>

	<mechanismTarget stateIdentifier="BACK_HOOK_ROTATE_A"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="19.0"
					 secondValue="66.0"
					 robotPitch="11.6"/>

	<mechanismTarget stateIdentifier="BACK_HOOK_LIFT_ROBOT"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="5.0"
					 secondValue="66.0"
					 robotPitch="11.6"/>

	<mechanismTarget stateIdentifier="BACK_HOOK_REST"
	                 controlDataIdentifier="closedloopposinches"
	                 controlDataIdentifier2="closedloopposdegrees"
					 value="19.0"
					 secondValue="66.0"
					 robotPitch="11.6"/>


</statedata>

=== markhhoover/BaseRepository2023Beta/src/main/deploy/states/indexer.xml
<?xml version="1.0"?>
<!DOCTYPE statedata SYSTEM "stateData.dtd">
<statedata>
	<controlData identifier="openloop" 
	             mode="PERCENT_OUTPUT"/>
	<mechanismTarget stateIdentifier="INDEX_LEFT"
	                 controlDataIdentifier="openloop"
                     controlDataIdentifier2="openloop"
					 value="1.0"
                     secondValue="0.0"/>
	<mechanismTarget stateIdentifier="INDEX_RIGHT"
	                 controlDataIdentifier="openloop"
                     controlDataIdentifier2="openloop"
					 value="0.0"
                     secondValue="1.0"/>
    <mechanismTarget stateIdentifier="EXPEL_LEFT"
                     controlDataIdentifier="openloop"
                     controlDataIdentifier2="openloop"
                     value="-1.0"
                     secondValue="0.0"/>
    <mechanismTarget stateIdentifier="EXPEL_RIGHT"
                     controlDataIdentifier="openloop"
                     controlDataIdentifier2="openloop"
                     value="0.0"
                     secondValue="-1.0"/>
    <mechanismTarget stateIdentifier="INDEXER_OFF"
                     controlDataIdentifier="openloop"
                     controlDataIdentifier2="openloop"
                     value="0.0"
                     secondValue="0.0"/>
    <mechanismTarget stateIdentifier="INDEX_BOTH"
                     controlDataIdentifier="openloop"
                     controlDataIdentifier2="openloop"
                     value="1.0"
                     secondValue="1.0"/>
                     
</statedata>
